# Use postgres/example user/password credentials
version: '3.1'

services:

  postgres-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432
    shm_size: 1g
    volumes:
      - ~/postgres-data:/var/lib/postgresql/data

  clickhouse-db:
    image: clickhouse/clickhouse-server
    restart: always
    ports:
      - 8123:8123
      - 9000:9000
    volumes:
      - ~/clickhouse-data:/var/lib/clickhouse/
